name: MacOS GUI

on:
  push:
    branches:
      - master
      - v2.2x
    paths:
      - '.github/workflows/build-gui_mac.yml'
      - 'gui/src/**'

  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/build-gui_mac.yml'
      - 'gui/src/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11

    steps:
      - name: Select XCode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.5.1'

      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==2.1.*'
          version: '6.4.1'
          modules: 'qtserialport'
          setup-python: false

      - name: Build
        working-directory: ${{github.workspace}}
        run: |
          cd gui/src
          ls
          qmake HeadTracker.pro
          make

#      - name: List Files
#        working-directory: ${{github.workspace}}
#        run: |
#          ls -la gui/src/HeadTracker.app/
#          ls -la gui/src/HeadTracker.app/Contents
#          ls -la gui/src/HeadTracker.app/Contents/MacOs
#          lipo -detailed_info gui/src/HeadTracker.app/Contents/MacOS/HeadTracker

      - name: MacDeployQT
        working-directory: ${{github.workspace}}
        run: |
          mkdir output
          cp -R gui/src/HeadTracker.app output/HeadTracker.app
          cp gui/src/css/stylesheet.css output/HeadTracker.app/Contents/MacOs
          cp gui/src/css/Background.svg output/HeadTracker.app/Contents/MacOs
          cd output
          macdeployqt HeadTracker.app -verbose=2

# https://localazy.com/blog/how-to-automatically-sign-macos-apps-using-github-actions  
# https://successfulsoftware.net/2018/11/16/how-to-notarize-your-software-on-macos/        

      - name: Codesign executable
        working-directory: ${{github.workspace}}/output
        env: 
          APPLE_DEV_IDENTITY: ${{ secrets.APPLE_DEV_IDENTITY}} 
          APPLE_DEV_USER: ${{ secrets.DEV_USER }}
          APPLE_DEV_PASS: ${{ secrets.DEV_PASS }}
        run: |
          macdeployqt HeadTracker.app -dmg -sign-for-notarization="${APPLE_DEV_IDENTITY}"
          mv HeadTracker.dmg HeadTracker-${VERSION}.dmg

          # echo "--> Start Notarization process"
          # response=$(xcrun altool -t osx -f HeadTracker-${VERSION}.dmg --primary-bundle-id org.accelero.headtracker --notarize-app -u ${APPLE_DEV_USER} -p ${APPLE_DEV_PASS})
          # requestUUID=$(echo "${response}" | tr ' ' '\n' | tail -1)

          # while true; do
          #   echo "--> Checking notarization status"

          #   statusCheckResponse=$(xcrun altool --notarization-info ${requestUUID} -u ${APPLE_DEV_USER} -p ${APPLE_DEV_PASS})

          #   isSuccess=$(echo "${statusCheckResponse}" | grep "success")
          #   isFailure=$(echo "${statusCheckResponse}" | grep "invalid")

          #   if [[ "${isSuccess}" != "" ]]; then
          #       echo "Notarization done!"
          #       xcrun stapler staple -v HeadTracker-${VERSION}.dmg
          #       echo "Stapler done!"
          #       break
          #   fi
          #   if [[ "${isFailure}" != "" ]]; then
          #       echo "Notarization failed"
          #       return 1
          #   fi
          #   echo "Notarization not finished yet, sleep 2m then check again..."
          #   sleep 120
          # done

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: HeadTracker_MacOs
          path: ${{github.workspace}}/output
          retention-days: 60
