name: HT Linux GUI

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-gui_linux.yml'
      - 'gui/src/**'

  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/build-gui_linux.yml'
      - 'gui/src/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          target: 'desktop'
          modules: 'qtserial'
          install-deps: 'true'

      - name: Build
        working-directory: ${{github.workspace}}        
        run: |
          cd gui/src
          dir
          qmake HeadTracker.pro
          make -j `nproc`

      - name: LinDeployQT
        working-directory: ${{github.workspace}}
        run: |
          mkdir ../usr
          mkdir ../usr/bin
          mkdir ../usr/share
          mkdir ../usr/share/applications          
          mkdir ../usr/share/icons
          mkdir ../usr/share/icons/hicolor
          mkdir ../usr/share/icons/hicolor/256x256
          mkdir ../usr/share/icons/hicolor/256x256/apps
          cp gui/src/HeadTracker ../usr/bin/
          cp gui/src/css/stylesheet.css ../usr/bin/
          cp gui/src/css/Background.svg ../usr/bin/
          cp gui/src/images/Icon256.png ../usr/share/icons/hicolor/256x256/apps/default.png
          echo -e "[Desktop Entry]\nType=Application\nName=HeadTracker\nExec=HeadTracker\nIcon=default\nCategories=Utility;" > ../usr/share/applications/headtracker.desktop
          wget https://github.com/dlktdr/HeadTracker/raw/master/gui/bin/bossac_lin
          chmod a+x ./bossac_lin
          mv ./bossac_lin ../usr/bin/
          cd ..
          wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
          chmod a+x ./linuxdeployqt-continuous-x86_64.AppImage
          ./linuxdeployqt-continuous-x86_64.AppImage usr/share/applications/headtracker.desktop -appimage -verbose=2

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: headtracker_linux_appimage
          path: ${{github.workspace}}/HeadTracker*.AppImage
          retention-days: 60