# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/build-firmware.yml'
      - 'firmware/src/**'
    
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/build-firmware.yml'
      - 'firmware/src/**'
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: shaguarger/platformio
      volumes:
        - ${{ github.workspace }}:/src

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
    
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Set up Python
        uses: actions/setup-python@v2
        
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      # Runs a single command using the runners shell
      - name: Build Firmware
        run: |
          cd /src/firmware/src
          pio run          

      # Runs a set of commands using the runners shell          
      - name: Package Firmware
        uses: 'actions/upload-artifact@v2'
        with:
          name: buildfirmware
          path: |
            /src/firmware/src/.pio/build/*/*.bin
          retention-days: 60
          if-no-files-found: error